FROM python:3.8.5-buster

VOLUME /data

RUN apt-get update && apt-get -y --no-install-recommends install nginx supervisor

COPY requirements.txt .
RUN pip install -r requirements.txt

ADD . /ancile/

WORKDIR /ancile

CMD ["/ancile/server/run.sh"]
